services:
  - type: web
    name: ai-study-assistant-api
    env: python
    region: oregon
    plan: free
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: MODEL_NAME
        value: gemini-2.5-flash
      - key: CRYPTOGRAPHY_DONT_BUILD_RUST
        value: "1"
      - key: USE_MYPYC
        value: "0"
      - key: PORT
        fromService:
          type: web
          name: ai-study-assistant-api
          property: port